### PR TITLE
Moving invoice model factory migration to package

### PR DESCRIPTION
**Pull request by phuclh**
- Move model + factory + migration file.
- Delete those files from TGER repo.

### CODE REVIEW

**Review by drewroberts — APPROVED** [review]
Thank you, Phuc. 🌱

We'll add more functionality to this package in the coming month since it is not currently being used in an application.

**Comment by drewroberts** [comment]
@joshtorres I'm merging this, but wanted to make sure you saw this PR.

**Comment by joshtorres** [comment]
Thanks looking now

**Review by joshtorres — COMMENTED** [review]
looks good

**Pull request merged**
